# Generated by Django 3.0.3 on 2020-03-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='var',
            new_name='Variable',
        ),
    ]
