# Generated by Django 3.0.3 on 2020-03-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_auto_20200303_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='abbr',
            new_name='abbreviation',
        ),
    ]
