# Generated by Django 3.0.3 on 2020-03-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20200304_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
