# Generated by Django 3.0.3 on 2020-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='param',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equation',
            name='formulaID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equation',
            name='inversion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
