# Generated by Django 3.0.3 on 2020-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='formulaID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equation',
            name='inversion',
            field=models.IntegerField(blank=True),
        ),
    ]
