# Generated by Django 3.0.3 on 2020-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0002_auto_20200324_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='inputcount',
            field=models.IntegerField(null=True),
        ),
    ]
