# Generated by Django 3.0.3 on 2020-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaula',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
