# Generated by Django 3.0.3 on 2020-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formaula_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formaula',
            new_name='Formula',
        ),
    ]
