# Generated by Django 3.0.3 on 2020-03-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_auto_20200304_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formula',
            new_name='Formula1',
        ),
    ]
