# Generated by Django 3.0.3 on 2020-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0007_auto_20200310_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='express1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='express2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='express3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='express4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='param1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formula',
            name='param2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formula',
            name='param3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formula',
            name='param4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
