# Generated by Django 3.0.3 on 2020-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0008_auto_20200310_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='express1',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='express2',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='express3',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='express4',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='param1',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='param2',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='param3',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='param4',
        ),
        migrations.AddField(
            model_name='formula',
            name='formulaID',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formula',
            name='inversion',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
